sudo: required

language: java

services:
  - docker
  
before_install:
  - docker build -t ryan000011/green .
  - docker ps -a
  - docker run ryan000011/green --name cont green /bin/sh -c "ant; ant test;"
  - docker logs -f run
