sudo: required

language: java

services:
  - docker
  
before_install:
  - docker build -t dockergreen .

script:
  - docker run -d --name container dockergreen /bin/sh -c "ant; ant test;"
  - docker logs --follow --details container
